# Generated by Django 3.0 on 2019-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='x',
            new_name='accelx',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='y',
            new_name='accely',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='z',
            new_name='accelz',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gyrox',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gyroy',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='gyroz',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='velx',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='vely',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='velz',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
