# Generated by Django 3.0 on 2019-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20191217_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='instant',
            field=models.DateTimeField(),
        ),
    ]
