# Generated by Django 3.0 on 2019-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20191217_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='activity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
