# Generated by Django 3.0.2 on 2020-01-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_sensordata_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='velx',
            new_name='orientx',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='vely',
            new_name='orienty',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='velz',
            new_name='orientz',
        ),
    ]
